Resolvendo problemas

diff --git a/.github/workflows/workflow-pr.yml b/.github/workflows/workflow-pr.yml
--- a/.github/workflows/workflow-pr.yml
+++ b/.github/workflows/workflow-pr.yml
@@ -18,41 +18,53 @@ jobs:
           POSTGRES_DB: test_db
 
     steps:
-      - name: Wait for PostgreSQL to initialize
-        run: sleep 10
-      - uses: actions/checkout@v3
+    - name: Wait for PostgreSQL to initialize
+      run: sleep 10
 
-      - name: Set up Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: 3.12
+    - uses: actions/checkout@v3
 
-      - name: Install poetry
-        run: |
-          pip install -U pip
-          pip install poetry
-          poetry install
-        env:
-          POETRY_VIRTUALENVS_CREATE: false
+    - name: Set up Python
+      uses: actions/setup-python@v3
+      with:
+        python-version: 3.12
 
-      - name: Verify PostgreSQL is running
-        run: |
-          pg_isready -h postgres -p 5432 -U postgres
-        env:
-          PGPASSWORD: postgres
+    - name: Install poetry
+      run: |
+        pip install -U pip
+        pip install poetry
+        poetry install
+      env:
+        POETRY_VIRTUALENVS_CREATE: false
 
-      - name: Run migrations
-        run: |
-          poetry run python manage.py migrate
+    - name: Verify PostgreSQL is running
+      run: |
+        for i in {1..30}; do
+          if pg_isready -h postgres -p 5432 -U postgres; then
+            echo "PostgreSQL is ready!"
+            break
+          fi
+          echo "Waiting for PostgreSQL... $i seconds"
+          sleep 1
+        done
+        if ! pg_isready -h postgres -p 5432 -U postgres; then
+          echo "PostgreSQL failed to start in time."
+          exit 1
+        fi
+      env:
+        PGPASSWORD: postgres
 
-      - name: Test
-        run: |
-          poetry run python manage.py test
+    - name: Run migrations
+      run: |
+        poetry run python manage.py migrate
 
-      - name: Wemake Python Styleguide
-        uses: wemake-services/wemake-python-styleguide@0.16.0
-        continue-on-error: true
-        with:
-          reporter: 'github-pr-review'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Test
+      run: |
+        poetry run python manage.py test
+
+    - name: Wemake Python Styleguide
+      uses: wemake-services/wemake-python-styleguide@0.16.0
+      continue-on-error: true
+      with:
+        reporter: 'github-pr-review'
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
